Testing: Restrict matplotlib version to <3 for testing as pip install fails on travis
Error message in Travis build log (for Python 3.6 install) is:
error: Setup script exited with
Matplotlib 3.0+ does not support Python 2.x, 3.0, 3.1, 3.2, 3.3, or 3.4.
Beginning with Matplotlib 3.0, Python 3.5 and above is required